server:
  port: 7082
spring:
  application:
    name: flowerpot-admin-web

  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flowerpot?useSSL=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    schema:
      - classpath:flowerpot-system.sql
      - classpath*:flowerpot-mailbox.sql
      - classpath*:flowerpot-storage.sql
      - classpath*:flowerpot-authorize.sql
    initialization-mode: always # 打开这个才会执行上面所创建的SQL


# Mybatis Plus
mybatis-plus:
  global-config:
    db-config:
      # 逻辑删除
      logic-delete-field: effective
      # 删除值为 0
      logic-delete-value: 0
      # 未删除值为 1
      logic-not-delete-value: 1

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
